# Generated by Django 5.2.1 on 2025-05-22 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_data', models.JSONField(help_text="Données de l'itinéraire au format GeoJSON")),
                ('estimated_distance', models.FloatField(help_text='Distance estimée en km')),
                ('estimated_duration', models.IntegerField(help_text='Durée estimée en minutes')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='orders.order')),
            ],
        ),
    ]
