# Generated by Django 5.2.1 on 2025-05-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('delivery_address', models.TextField()),
                ('delivery_latitude', models.FloatField()),
                ('delivery_longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_pickup_time', models.DateTimeField()),
                ('estimated_delivery_time', models.DateTimeField()),
                ('actual_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('picked_up', 'Prise en charge'), ('in_transit', 'En cours de livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('service_type', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('same_day', 'Même jour')], default='standard', max_length=20)),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_insurance', models.BooleanField(default=False)),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('picked_up', 'Prise en charge'), ('in_transit', 'En cours de livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(help_text='Poids en kg')),
                ('size', models.CharField(choices=[('small', 'Petit'), ('medium', 'Moyen'), ('large', 'Grand'), ('extra_large', 'Très grand')], max_length=20)),
                ('is_fragile', models.BooleanField(default=False)),
                ('requires_signature', models.BooleanField(default=False)),
            ],
        ),
    ]
